title: PadPalon
description: >-
  This page will serve as an outlet for information on some of my projects. On here I will only publish the things I
  find to actually have some value.
baseurl: ""
url: "https://padpalon.ch"

theme: minima
plugins:
  - jekyll-feed

collections:
  games:
    output: true
    permalink: /games/:path/
    sort_by: order
  music:
    output: true
    permalink: /music/:path/
    sort_by: order
  jobs:
    output: true
    permalink: /jobs/:path/
    sort_by: order
  cds:
    sort_by: artist

show_excerpts: true
excerpt_separator: <!--more-->

header_pages:
  - about.md
  - articles.md
  - career.md
  - gaming.md
  - music.md
  - collections.md

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/PadPalon" }
    - { platform: bluesky,  user_url: "https://bsky.app/profile/padpalon.ch" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/luca-neukom/" }
    - { platform: youtube,  user_url: "https://www.youtube.com/@PadPalon" }

author:
  name: PadPalon