# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PadPalon
email: luca.neukom@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page will serve as an outlet for information on some of my projects. On here I will only publish the things I
  find to actually have some value.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://padpalon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PadPalon
github_username:  PadPalon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  games:
    output: true
    permalink: /games/:path/
    sort_by: order
  music:
    output: true
    permalink: /music/:path/
    sort_by: order
  jobs:
    output: true
    permalink: /jobs/:path/
    sort_by: order
  cds:
    sort_by: artist

show_excerpts: true
